language: node_js
node_js:
  - '9'
script:
  - npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: carescalculator.com
  on:
    branch: master
  skip_cleanup: true
env:
  - THIS_IS_ON_TRAVIS_AND_SANDBOX_IS_NOT_ALLOWED=true
